### ISSUE TITLE
Settings for polling interval?

### ISSUE THREAD

**Issue by cyrusauyeungc** [ThomasMeyer1970/homebridge-Fronius#1]
hello mate, thanks for your great work. 

May i know would there be any chance that the polling interval could be set (or whats the existing interval)?

**Comment by ThomasMeyer1970** [comment]
Hello,

the polling interval is 5 Sec. 

You can change it in the code:

 async getCurrentAmbientLightLevelHandler (callback)
 	{
 	   setInterval(
 		   {	
 	           getValue = await getAccessoryValue(this.ip, this.inverter_data)

 	           callback(null, getValue)
                    }, 5 * 1000);

Please note that this plugin is no longer actively developed.

best regards

**Comment by cyrusauyeungc** [comment]
Appreciate that mate!
